spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://locahost:3306/ll?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true 
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: edu.swjtuhc.demo.mapper